language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2.4
  - 2.3.0
  - 2.4.0
  - ruby-head
  - jruby
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
before_install:
  - "sudo apt-get install libnotify4"
  - "gem install bundler"
